// <auto-generated />
namespace PMSAWebMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pwd_approve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pwd_approve));
        
        string IMigrationMetadata.Id
        {
            get { return "201911241707434_pwd_approve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
