//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlNames() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ControlNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Button 的當地語系化字串。
        /// </summary>
        internal static string Control_Button {
            get {
                return ResourceManager.GetString("Control.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CheckBox 的當地語系化字串。
        /// </summary>
        internal static string Control_CheckBox {
            get {
                return ResourceManager.GetString("Control.CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GridView 的當地語系化字串。
        /// </summary>
        internal static string Control_GridView {
            get {
                return ResourceManager.GetString("Control.GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HyperLink 的當地語系化字串。
        /// </summary>
        internal static string Control_HyperLink {
            get {
                return ResourceManager.GetString("Control.HyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image 的當地語系化字串。
        /// </summary>
        internal static string Control_Image {
            get {
                return ResourceManager.GetString("Control.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImageButton 的當地語系化字串。
        /// </summary>
        internal static string Control_ImageButton {
            get {
                return ResourceManager.GetString("Control.ImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Label 的當地語系化字串。
        /// </summary>
        internal static string Control_Label {
            get {
                return ResourceManager.GetString("Control.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LinkButton 的當地語系化字串。
        /// </summary>
        internal static string Control_LinkButton {
            get {
                return ResourceManager.GetString("Control.LinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 List 的當地語系化字串。
        /// </summary>
        internal static string Control_List {
            get {
                return ResourceManager.GetString("Control.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Literal 的當地語系化字串。
        /// </summary>
        internal static string Control_Literal {
            get {
                return ResourceManager.GetString("Control.Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Panel 的當地語系化字串。
        /// </summary>
        internal static string Control_Panel {
            get {
                return ResourceManager.GetString("Control.Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RadioButton 的當地語系化字串。
        /// </summary>
        internal static string Control_RadioButton {
            get {
                return ResourceManager.GetString("Control.RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TextBox 的當地語系化字串。
        /// </summary>
        internal static string Control_TextBox {
            get {
                return ResourceManager.GetString("Control.TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 undefined 的當地語系化字串。
        /// </summary>
        internal static string Control_undefined {
            get {
                return ResourceManager.GetString("Control.undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Validator 的當地語系化字串。
        /// </summary>
        internal static string Control_Validator {
            get {
                return ResourceManager.GetString("Control.Validator", resourceCulture);
            }
        }
    }
}
