//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryDtl()
        {
            this.StockInDtl = new HashSet<StockInDtl>();
            this.StockOutDtl = new HashSet<StockOutDtl>();
        }
    
        public int InventoryDtlOID { get; set; }
        public string InventoryCode { get; set; }
        public string WarehouseCode { get; set; }
        public string InventoryCategoryCode { get; set; }
        public string SourceListID { get; set; }
        public string PartNumber { get; set; }
        public int UnitsInStock { get; set; }
        public int UnitsOnStockOutOrder { get; set; }
        public int UnitsOnStockInOrder { get; set; }
        public Nullable<int> SafetyQty { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateEmployeeID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedEmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual InventoryCategory InventoryCategory { get; set; }
        public virtual Part Part { get; set; }
        public virtual SourceList SourceList { get; set; }
        public virtual WarehouseInfo WarehouseInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInDtl> StockInDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutDtl> StockOutDtl { get; set; }
    }
}
