//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSAEntities : DbContext
    {
        public PMSAEntities()
            : base("name=PMSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthRole> AuthRole { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfo { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FuncModule> FuncModule { get; set; }
        public virtual DbSet<GenerateID> GenerateID { get; set; }
        public virtual DbSet<InventoryCategory> InventoryCategory { get; set; }
        public virtual DbSet<InventoryDtl> InventoryDtl { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<PartCategory> PartCategory { get; set; }
        public virtual DbSet<PartCategoryDtl> PartCategoryDtl { get; set; }
        public virtual DbSet<PartUnit> PartUnit { get; set; }
        public virtual DbSet<POChanged> POChanged { get; set; }
        public virtual DbSet<POChangedCategory> POChangedCategory { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductPart> ProductPart { get; set; }
        public virtual DbSet<PRPORelation> PRPORelation { get; set; }
        public virtual DbSet<PRPORelationTemp> PRPORelationTemp { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderDtl> PurchaseOrderDtl { get; set; }
        public virtual DbSet<PurchaseOrderDtlTemp> PurchaseOrderDtlTemp { get; set; }
        public virtual DbSet<PurchaseOrderReceive> PurchaseOrderReceive { get; set; }
        public virtual DbSet<PurchaseOrderReceiveDtl> PurchaseOrderReceiveDtl { get; set; }
        public virtual DbSet<PurchaseOrderTemp> PurchaseOrderTemp { get; set; }
        public virtual DbSet<PurchaseRequisition> PurchaseRequisition { get; set; }
        public virtual DbSet<PurchaseRequisitionDtl> PurchaseRequisitionDtl { get; set; }
        public virtual DbSet<PurchaseRequisitionDtlTemp> PurchaseRequisitionDtlTemp { get; set; }
        public virtual DbSet<PurchaseRequisitionTemp> PurchaseRequisitionTemp { get; set; }
        public virtual DbSet<RoleModuleList> RoleModuleList { get; set; }
        public virtual DbSet<ShipNotice> ShipNotice { get; set; }
        public virtual DbSet<ShipNoticeDtl> ShipNoticeDtl { get; set; }
        public virtual DbSet<SignFlow> SignFlow { get; set; }
        public virtual DbSet<SignFlowDtl> SignFlowDtl { get; set; }
        public virtual DbSet<SourceList> SourceList { get; set; }
        public virtual DbSet<SourceListDtl> SourceListDtl { get; set; }
        public virtual DbSet<StockIn> StockIn { get; set; }
        public virtual DbSet<StockInDtl> StockInDtl { get; set; }
        public virtual DbSet<StockOut> StockOut { get; set; }
        public virtual DbSet<StockOutDtl> StockOutDtl { get; set; }
        public virtual DbSet<SupplierAccount> SupplierAccount { get; set; }
        public virtual DbSet<SupplierInfo> SupplierInfo { get; set; }
        public virtual DbSet<SupplierRating> SupplierRating { get; set; }
        public virtual DbSet<WarehouseInfo> WarehouseInfo { get; set; }
    }
}
