//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POChanged()
        {
            this.PurchaseOrderDtl = new HashSet<PurchaseOrderDtl>();
            this.PurchaseOrderDtlTemp = new HashSet<PurchaseOrderDtlTemp>();
        }
    
        public int POChangedOID { get; set; }
        public string PurchaseOrderID { get; set; }
        public string POChangedCategoryCode { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequesterRole { get; set; }
        public string RequesterID { get; set; }
        public string PurchaseOrderDtlCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
    
        public virtual POChangedCategory POChangedCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtl> PurchaseOrderDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtlTemp> PurchaseOrderDtlTemp { get; set; }
        public virtual PurchaseOrderDtl PurchaseOrderDtl1 { get; set; }
    }
}
