//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRPORelation
    {
        public int PRPORelationOID { get; set; }
        public string PurchaseRequisitionID { get; set; }
        public string PurchaseRequisitionDtlCode { get; set; }
        public string PurchaseOrderID { get; set; }
        public string PurchaseOrderDtlCode { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual PurchaseOrderDtl PurchaseOrderDtl { get; set; }
        public virtual PurchaseRequisition PurchaseRequisition { get; set; }
        public virtual PurchaseRequisitionDtl PurchaseRequisitionDtl { get; set; }
    }
}
