//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisitionTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequisitionTemp()
        {
            this.PurchaseRequisitionDtlTemp = new HashSet<PurchaseRequisitionDtlTemp>();
        }
    
        public int PurchaseRequisitionOID { get; set; }
        public string ProductNumber { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime PRBeginDate { get; set; }
        public string ProcessStatus { get; set; }
        public string SignStatus { get; set; }
        public Nullable<int> SignFlowOID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisitionDtlTemp> PurchaseRequisitionDtlTemp { get; set; }
        public virtual SignFlow SignFlow { get; set; }
    }
}
