//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderReceive()
        {
            this.PurchaseOrderReceiveDtl = new HashSet<PurchaseOrderReceiveDtl>();
            this.StockIn = new HashSet<StockIn>();
        }
    
        public int PurchaseOrderReceiveOID { get; set; }
        public string PurchaseOrderReceiveID { get; set; }
        public string PurchaseOrderID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string PurchaseEmployeeID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierAccountID { get; set; }
        public string SignStatus { get; set; }
        public Nullable<int> SignFlowOID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual SignFlow SignFlow { get; set; }
        public virtual SupplierAccount SupplierAccount { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderReceiveDtl> PurchaseOrderReceiveDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockIn> StockIn { get; set; }
    }
}
