//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderReceiveDtl
    {
        public int PurchaseOrderReceiveDtlOID { get; set; }
        public string PurchaseOrderReceiveDtlCode { get; set; }
        public string PurchaseOrderReceiveID { get; set; }
        public string PurchaseOrderDtlCode { get; set; }
        public int PurchaseQty { get; set; }
        public int PurchaseAmount { get; set; }
        public int RejectQty { get; set; }
        public int AcceptQty { get; set; }
        public string RejectReason { get; set; }
        public string Remark { get; set; }
    
        public virtual PurchaseOrderDtl PurchaseOrderDtl { get; set; }
        public virtual PurchaseOrderReceive PurchaseOrderReceive { get; set; }
    }
}
