//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipNotice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipNotice()
        {
            this.ShipNoticeDtl = new HashSet<ShipNoticeDtl>();
        }
    
        public int ShipNoticeOID { get; set; }
        public string ShipNoticeID { get; set; }
        public string PurchaseOrderID { get; set; }
        public System.DateTime ShipDate { get; set; }
        public string EmployeeID { get; set; }
        public string CompanyCode { get; set; }
        public string SupplierAccountID { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual SupplierAccount SupplierAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipNoticeDtl> ShipNoticeDtl { get; set; }
    }
}
