//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignFlowDtl
    {
        public int SignFlowDtlOID { get; set; }
        public int SignFlowOID { get; set; }
        public string ApprovingOfficerID { get; set; }
        public string SignOpinion { get; set; }
        public string SignStatusCode { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string SFDSendLetterState { get; set; }
        public Nullable<System.DateTime> SFDSendLetterDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SignFlow SignFlow { get; set; }
    }
}
