//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceListDtl
    {
        public int SourceListDtlOID { get; set; }
        public string SourceListID { get; set; }
        public int QtyDemanded { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> DiscountBeginDate { get; set; }
        public Nullable<System.DateTime> DiscountEndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual SourceList SourceList { get; set; }
    }
}
