//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SourceList()
        {
            this.InventoryDtl = new HashSet<InventoryDtl>();
            this.PurchaseOrderDtl = new HashSet<PurchaseOrderDtl>();
            this.PurchaseOrderDtlTemp = new HashSet<PurchaseOrderDtlTemp>();
            this.SourceListDtl = new HashSet<SourceListDtl>();
        }
    
        public int SourceListOID { get; set; }
        public string SourceListID { get; set; }
        public string PartNumber { get; set; }
        public int QtyPerUnit { get; set; }
        public Nullable<int> MOQ { get; set; }
        public int UnitPrice { get; set; }
        public string SupplierCode { get; set; }
        public int UnitsInStock { get; set; }
        public int UnitsOnOrder { get; set; }
        public Nullable<int> SafetyQty { get; set; }
        public Nullable<int> EXP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDtl> InventoryDtl { get; set; }
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtl> PurchaseOrderDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtlTemp> PurchaseOrderDtlTemp { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SourceListDtl> SourceListDtl { get; set; }
    }
}
