//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierInfo()
        {
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.PurchaseOrderReceive = new HashSet<PurchaseOrderReceive>();
            this.PurchaseOrderTemp = new HashSet<PurchaseOrderTemp>();
            this.PurchaseRequisitionDtl = new HashSet<PurchaseRequisitionDtl>();
            this.PurchaseRequisitionDtlTemp = new HashSet<PurchaseRequisitionDtlTemp>();
            this.SourceList = new HashSet<SourceList>();
            this.SupplierAccount = new HashSet<SupplierAccount>();
        }
    
        public int SupplierInfoOID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string TaxID { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public Nullable<int> SupplierRatingOID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderReceive> PurchaseOrderReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderTemp> PurchaseOrderTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisitionDtl> PurchaseRequisitionDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisitionDtlTemp> PurchaseRequisitionDtlTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SourceList> SourceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierAccount> SupplierAccount { get; set; }
        public virtual SupplierRating SupplierRating { get; set; }
    }
}
